### ISSUE TITLE
Create script to get BoardEx data.

### ISSUE THREAD

**Issue by iangow** [mccgr/wrds_pg#28]
First, query WRDS's PostgreSQL database for each BoardEx schema to get a list of tables.
Second, use Python WRDS-PostgreSQL script to get each table in each schema.

Need to find sample code for first step, which should not be too difficult.

**Comment by iangow** [comment]
@jamespkav See above.

**Comment by jamespkav** [comment]
I have one. I've occasionally used it against your server to figure out what tables I'm using for various MCCGR projects

**Comment by iangow** [comment]
If so, please share it as a comment here.

**Comment by jamespkav** [comment]
A code like this should do the trick:
`tst<-dbGetQuery(pg,"SELECT * FROM information_schema.tables WHERE table_schema = 'boardex'")`

**Comment by iangow** [comment]
@jamespkav:

Thanks. The code I'm using is based on Python and suppresses some of these details (sometimes the organisation of this behind-the-scenes information changes).

But I should be able to cobble something together fairly quickly.

**Comment by iangow** [comment]
I just did this:

```
pg_dump --host wrds-pgdata.wharton.upenn.edu --username "iangow" --port 9737 \
    --format custom --no-tablespaces -O --verbose --schema "boardex_eur" "wrds" \
    | pg_restore --host localhost --username "igow" --dbname "crsp"  \
    --verbose --no-tablespaces --clean
pg_dump --host wrds-pgdata.wharton.upenn.edu --username "iangow" --port 9737 \
    --format custom --no-tablespaces -O --verbose --schema "boardex_uk" "wrds" \
    | pg_restore --host localhost --username "igow" --dbname "crsp"  
    --verbose --no-tablespaces --clean
```

**Comment by iangow** [comment]
The SAS files WRDS has for BoardEx is just too messed up to be useable.

**Comment by iangow** [comment]
We should check (somehow) that the US and ROW data are as up-to-date as the UK/Europe data. If not then we need to update the former data sets. Here is code for that:

```
pg_dump --host wrds-pgdata.wharton.upenn.edu --username "iangow" --port 9737 \
    --format custom --no-tablespaces -O --verbose --schema "boardex_us" "wrds" \
    | pg_restore --host localhost --username "igow" --dbname "crsp"  \
    --verbose --no-tablespaces --clean
pg_dump --host wrds-pgdata.wharton.upenn.edu --username "iangow" --port 9737 \
    --format custom --no-tablespaces -O --verbose --schema "boardex_row" "wrds" \
    | pg_restore --host localhost --username "igow" --dbname "crsp"  
    --verbose --no-tablespaces --clean
```

**Comment by jamespkav** [comment]
Results of checking boardex dates between `boardex_na` and `boardex_eur` are as follows:

```
> datehighna
# A tibble: 1 x 1
  announcementdate
*           <date>
1       2017-07-07
> datehigheur
# A tibble: 1 x 1
  announcementdate
*           <date>
1       2018-03-16
```
So it appears Europe may be a little more recent.

**Comment by iangow** [comment]
@jamespkav 

I ran the following SQL, which should set up to be able to run the `pg_dump` above:

```sql
GRANT ALL ON ALL TABLES IN SCHEMA boardex_uk TO boardex;
GRANT ALL ON ALL TABLES IN SCHEMA boardex_eur TO boardex;
GRANT ALL ON ALL TABLES IN SCHEMA boardex_na TO boardex;
GRANT ALL ON ALL TABLES IN SCHEMA boardex_row TO boardex;
GRANT USAGE ON SCHEMA boardex_na TO boardex;
GRANT USAGE ON SCHEMA boardex_row TO boardex;
GRANT USAGE ON SCHEMA boardex_uk TO boardex;
GRANT USAGE ON SCHEMA boardex_eur TO boardex;
GRANT boardex TO mccgr;
```

**Comment by lucieluyiliu** [comment]
> I just did this:
> 
> ```
> pg_dump --host wrds-pgdata.wharton.upenn.edu --username "iangow" --port 9737 \
>     --format custom --no-tablespaces -O --verbose --schema "boardex_eur" "wrds" \
>     | pg_restore --host localhost --username "igow" --dbname "crsp"  \
>     --verbose --no-tablespaces --clean
> pg_dump --host wrds-pgdata.wharton.upenn.edu --username "iangow" --port 9737 \
>     --format custom --no-tablespaces -O --verbose --schema "boardex_uk" "wrds" \
>     | pg_restore --host localhost --username "igow" --dbname "crsp"  
>     --verbose --no-tablespaces --clean
> ```

Hi Ian ,

 I am using trying to use pg_dump to import a wrds schema to a remote pgsql server using the same code but I got the following error: 
> ```
>pg_restore: [archiver] input file is too short (read 0, expected 5)


If I pg_dump to .sql, when I pg_restore I got a bunch of errors relationship does not exist and role wrdsadmin does not exist.

I know this is a really silly question . Any idea what went wrong? Thanks so much!

**Comment by iangow** [comment]
If you are using Windows, the `\` may not work. If you remove the `\` and put the code on one line, it may work.

Errors about tables not existing arise from `--clean` and don't really matter. And the one about `wrdsadmin` shouldn't matter either.

**Comment by iangow** [comment]
I don't know whether `|` works on Windows, however.

**Comment by jamespkav** [comment]
If I can jump in @iangow, for `cmd.exe` on windows the line separator is `^`. So perhaps this might work for @lucieluyiliu.

**Comment by lucieluyiliu** [comment]
Thanks a ton! @iangow  and @jamespkav I am running on linux so system is not a problem. It is puzzling that if I set format to custom, pg_dump returns a zero size dump file (therefore pg_restore returns file too short error).  If I set format to plain text it returns a dump file way smaller than the schema I'm importing (i.e. it contains some sql commands but not the data). Any thoughts?

**Comment by iangow** [comment]
Check that you have access to the data. Use `psql` and run a query against the WRDS server (`SELECT * FROM boardex_eur.some_table LIMIT 10`).

**Comment by lucieluyiliu** [comment]
Thanks! @iangow I do have access to the shema I'm trying to retrieve (which is factset) and I can query from the schema but I have not succeeded pg_pumping it. 
The pg_dump verbose shows that it is reading all tables in the schema.  but it seems that pg_dump does not export the actual data. In the pg_restore stage I got a long list of errors:  relation "some table" does not exist. For example:

```
pg_restore: connecting to database for restore
pg_restore: dropping ACL TABLE wrds_unadj_fund_holdings_hist
pg_restore: dropping VIEW wrds_unadj_fund_holdings_hist
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 54254; 1259 461261794 VIEW wrds_unadj_fund_holdings_hist wrdsadmn
pg_restore: [archiver (db)] could not execute query: ERROR:  view "wrds_unadj_fund_holdings_hist" does 

    Command was: DROP VIEW factset.wrds_unadj_fund_holdings_hist;
```
And for example:
```
pg_restore: creating ACL "factset.TABLE entity_type_map"
pg_restore: [archiver (db)] Error from TOC entry 235154; 0 0 ACL TABLE entity_type_map wrdsadmn
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "entity_type_map" does not exist
    Command was: GRANT SELECT ON TABLE entity_type_map TO testacct6;
GRANT SELECT ON TABLE entity_type_map TO harvard;
GRANT SELECT ON TABLE entity_type_map TO boc;
GRANT SELECT ON TABLE entity_type_map TO brandywine;
GRANT SELECT ON TABLE entity_type_map TO brocku;
```
So I think these are command wrds admin runs that I cannot run locally at my postgresql server to retrieve the tables. Any thoughts?

**Comment by iangow** [comment]
@lucieluyiliu See the updated script [here](https://github.com/mccgr/wrds_pg/blob/master/boardex/update_boardex.py), which works well. Getting the data from SAS is faster and generally gives better results than using data from the WRDS PostgreSQL database.
