### ISSUE TITLE
Document repository

### ISSUE THREAD

**Issue by iangow** [mccgr/wrds_pg#51]
@dingtq This repository contains the code I use to populate the MCCGR database server with data from WRDS. Most of the data is populated using the script `update_wrds.sh`, but data from Compustat, ISS, and CRSP are handled separately for various reasons (explained below).

Some "schemas" are simple. Just grab all the data from WRDS. Others get just subsets of the WRDS data (e.g., IBES) to save on space. In some cases, a lot of work is needed to clean up the data (e.g., Audit Analytics under `audit`).

I think we want to do two things:
1. Work out if there are any data sets that are missing that people would use.
2. Document what we have, especially in cases like Audit Analytics and CRSP where there's some value-added modifications that need explaining.

Perhaps the best way to handle (2) is for me to write documentation that you (and @bdcallen) can follow. Not sure how to do (1). Perhaps we should chat this week.

**Comment by dingtq** [comment]
@iangow I can chat any time this week except for 10:00-11:00 am tomorrow (21/05) morning. How about you, @bdcallen? Besides, any time on next Monday-Wednesday will work. 

Maybe we can start by documenting what we have, and get a list/document. Then we can use the list/document to solicit info regarding (1) from our colleagues. To do (2), it will be great to have a template as you advised, and then Ben and I could follow to complete the whole set.

**Comment by bdcallen** [comment]
@iangow @dingtq I could do 11am to 12pm tomorrow? Is that a little too soon after your other engagement tomorrow, Tony? Otherwise, I can do either Tuesday or Wednesday next week

**Comment by dingtq** [comment]
@iangow @bdcallen Either will work for me. @iangow Please let us know a good time for you so we can have a chat. :)

**Comment by iangow** [comment]
I can do 11am AEST today if they still works.

**Comment by dingtq** [comment]
@iangow @bdcallen Sounds great. I have sent out a Zoom meeting invitation. Chat soon!
