### ISSUE TITLE
Document diroffichange

### ISSUE THREAD

**Issue by iangow** [mccgr/wrds_pg#53]
@dingtq I will write documentation that answers these questions.

- What variables are included in main table?
- Which variables are omitted?
- Which variables (probably text) are put in a separate table (because they come from somewhere else)?

@dingtq @bdcallen You can see that there are other issues already here. This repository works, but needs a bit of work.

**Comment by dingtq** [comment]
@iangow That will be great! It could be hard for some databases, but potentially, it could be very helpful to suggest something regarding firm identifier and date identifier where feasible.

**Comment by iangow** [comment]
@dingtq Which Audit Analytics tables have you used in your own research? It may be helpful for me to do those sooner, as you would be more familiar with the data.

**Comment by dingtq** [comment]
Audan.Diroffichange

Tongqing (Tony) Ding

[cid:image001.png@01D6359F.FADDF250]

**Comment by iangow** [comment]
@dingtq I should have this ready to go for you tomorrow (so you could look at it next week). There might be a good task for someone like Yvonne or Yuchen to work on here.

**Comment by dingtq** [comment]
Sounds great, @iangow. After we set a good template with this one, we can plan on the documentation work for our primary databases. BTW, I mentioned this very briefly when Matt zoom chatted with me last week, and he was very happy with this "value-adding" work. :)

So how does Yvonne's schedule at our MCCGR look like? I remember she has been working on SE features etc. But I would love to have her working together on this if possible.

**Comment by iangow** [comment]
OK. @dingtq Over to you. Please take a look at the tables discussed [here](https://github.com/mccgr/wrds_pg/tree/master/audit). For example, could you easily do the analysis you've done using the versions of the tables that I have included?

Note that the changes I make to the underlying WRDS tables dramatically reduced their size. For example, `diroffichange` is 29.2GB as a SAS file on the WRDS server. But I reduce that to a main table of 163GB and separate textual-data tables that are less than a gigabyte.

**Comment by dingtq** [comment]
@iangow: The readme file is very easy to follow, especially with the sample code. Still, I made some modifications through ca6bd01246cf084c808e18ef54998cdaa08c91df and e17cb96f1296c373157233a07ca1071d4b925979 so that we could use them as a sample and consistent template for all other databases. Please let me know your thoughts and feel free to modify to improve them.
